# Numpy Notes

In [1]:
import numpy as np



In [5]:
#  priperties of array

array1 = np.array([[1, 2, 3],[2, 3, 4]])
print(array1)
print('number of dim: ', array1.ndim)
print('shape: ', array1.shape)
print('size: ', array1.size)

[[1 2 3]
 [2 3 4]]
number of dim:  2
shape:  (2, 3)
size:  6


In [9]:
#  define an arry

a = np.array([2, 23, 4])
b = np.array([22, 232, 42], dtype = np.float)
print(a.dtype)
print(b.dtype)

int32
float64


In [33]:
#  define all-1 array

c = np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
d = np.arange(10, 12, 0.4)
print(d)

[10.  10.4 10.8 11.2 11.6]


In [31]:
e = np.linspace(10, 16, 9)
print(e)

[10.   10.75 11.5  12.25 13.   13.75 14.5  15.25 16.  ]


In [30]:
f = np.arange(2,14).reshape(3,4)
print(f)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [36]:
#  numpy array calculation

print(np.median(f))
print(np.average(f))

7.5
7.5


In [37]:
# show two arrays to indicate the location of none zero items

np.nonzero(f)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [40]:
# sort

np.sort(f)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])